exclude: '.*snap$'
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
      exclude_types: [pem]
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      exclude: '.*migrations.*'
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
        'flake8-bugbear',
        # Flake8 failed to load plugin
        # 'flake8-print',     # Fail "pycodestyle.break_around_binary_operator"
        'flake8-debugger',  # Fail "pycodestyle.break_around_binary_operator"
      ]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
    - id: black
      args: [--line-length=100, --safe]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.761
  hooks:
    - id: mypy
      args: [--follow-imports=silent, --ignore-missing-imports]
- repo: https://github.com/prettier/prettier
  rev: '1.19.1'
  hooks:
    - id: prettier
      files: '^.*\.tsx?$'

