steps:
    - id: build
      name: 'gcr.io/kaniko-project/executor:latest'
      args: ["--destination=gcr.io/$PROJECT_ID/eleven7", "--cache=true"]

    - id: 'push'
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/${PROJECT_ID}/eleven7']

    - id: 'deploy '
      name: 'gcr.io/cloud-builders/gcloud'
      args: ["run", "deploy", "eleven7",
            "--platform", "managed",
            "--region", "asia-northeast1",
            "--image", "gcr.io/$PROJECT_ID/eleven7"]
